"""``deeperfly calibrate`` end to end: label an uncalibrated project, recover its rig.

The one test worth having here is :func:`test_the_whole_from_scratch_flow`, which walks the
path a new user actually takes -- videos, a project, hand labels, a solve -- and then checks
the recovered rig against the rig the labels were *generated* from. Everything else guards a
refusal: this command's job is as much to decline an under-determined solve as to perform a
good one.
"""

from __future__ import annotations

import numpy as np
import pytest
from helpers import CAMERA_NAMES, seven_camera_default

from deeperfly import cli
from deeperfly.gui.labels import Labels, labels_identity, save_labels
from deeperfly.project import Project

HEIGHT, WIDTH = 512, 960
SIZES = {name: (HEIGHT, WIDTH) for name in CAMERA_NAMES}
FOCAL = "22388.125"


def _labelled_project(
    tmp_path,
    truth,
    *,
    n_frames=6,
    n_kp=38,
    step=3,
    reviewed=True,
    noise=0.4,
):
    """A project whose one recording carries keypoint labels generated by ``truth``.

    No video files: the labels' *identity* is written directly, which is all `calibrate`
    reads. That keeps the test about the solve rather than about video decoding (which
    ``test_gui_uncalibrated`` already covers).

    Keypoints only -- dedicated static landmarks went in 0.3.0, so the animal IS the
    calibration target and this is what a from-scratch solve actually gets.
    """
    project = Project.create(tmp_path / "proj", name="scratch", skeleton="fly38")

    rec = tmp_path / "flyA"
    rec.mkdir()
    for name in CAMERA_NAMES:
        (rec / f"{name}.mp4").write_bytes(b"\0" * (1000 + len(name)))
    entry = project.add_recording(rec)

    rng = np.random.default_rng(0)
    n_views = len(CAMERA_NAMES)
    animal3d = rng.uniform(-4, 4, size=(n_frames, 38, 3))

    labels = Labels.empty(n_views, n_frames, 38)
    for t in range(n_frames):
        kp_px = np.asarray(truth.project(animal3d[t])) + rng.normal(
            0, noise, (n_views, 38, 2)
        )
        for v in range(n_views):
            for p in range(0, n_kp, step):
                labels.set_gt(v, t, p, kp_px[v, p])
        if reviewed:
            labels.set_reviewed(t, True)

    identity = labels_identity(
        point_names=list(project.skeleton().point_names),
        camera_names=list(CAMERA_NAMES),
        n_frames=n_frames,
        image_sizes=SIZES,
    )
    save_labels(project.labels_path(entry), labels, identity=identity)
    return project, entry


@pytest.fixture
def truth():
    return seven_camera_default().camera_group(image_sizes=SIZES)


def _centre_error_pct(truth, solved) -> float:
    a = np.stack([truth[n].position for n in CAMERA_NAMES])
    b = np.stack([solved[n].position for n in CAMERA_NAMES])
    ac, bc = a - a.mean(0), b - b.mean(0)
    u, s, vt = np.linalg.svd(bc.T @ ac)
    rot = u @ vt
    if np.linalg.det(rot) < 0:
        u[:, -1] *= -1
        rot = u @ vt
    scale = s.sum() / (bc**2).sum()
    err = np.linalg.norm(scale * (bc @ rot) - ac, axis=1)
    return float(100 * err.max() / np.linalg.norm(ac, axis=1).mean())


# -- the whole flow ------------------------------------------------------------


def test_nothing_is_accepted_without_the_flag(tmp_path, truth):
    """A bad solve must not be able to silently replace a good rig."""
    project, _ = _labelled_project(tmp_path, truth)
    cli.main(
        ["calibrate", str(project.root), "--focal-px", FOCAL, "--log-level", "error"]
    )
    assert (project.root / "calibrations" / "from-labels.toml").exists()
    assert Project.load(project.root).calibration is None


# -- refusals ------------------------------------------------------------------


def test_missing_intrinsics_names_the_three_ways_to_supply_them(tmp_path, truth):
    """Focal length is not recoverable from these labels, so it must not be guessed."""
    project, _ = _labelled_project(tmp_path, truth)
    with pytest.raises(SystemExit, match="no intrinsics source"):
        cli.main(["calibrate", str(project.root), "--log-level", "error"])


def test_a_project_with_no_labels_says_so(tmp_path):
    project = Project.create(tmp_path / "proj")
    with pytest.raises(SystemExit, match="nothing to calibrate from"):
        cli.main(["calibrate", str(project.root), "--log-level", "error"])
