"""``deeperfly calibrate`` end to end: label an uncalibrated project, recover its rig.

The one test worth having here is :func:`test_the_whole_from_scratch_flow`, which walks the
path a new user actually takes -- videos, a project, hand labels, a solve -- and then checks
the recovered rig against the rig the labels were *generated* from. Everything else guards a
refusal: this command's job is as much to decline an under-determined solve as to perform a
good one.
"""

from __future__ import annotations

import numpy as np
import pytest
from helpers import CAMERA_NAMES

from deeperfly import cli
from deeperfly.calibration import Calibration
from deeperfly.config import Config
from deeperfly.gui.labels import (
    Labels,
    LandmarkLabels,
    labels_identity,
    save_labels,
)
from deeperfly.landmarks import Landmark, LandmarkSet
from deeperfly.project import Project

HEIGHT, WIDTH = 512, 960
SIZES = {name: (HEIGHT, WIDTH) for name in CAMERA_NAMES}
FOCAL = "22388.125"


@pytest.fixture
def truth():
    return Config.default().camera_group(image_sizes=SIZES)


def _labelled_project(
    tmp_path,
    truth,
    *,
    n_static=6,
    n_frames=6,
    n_kp=38,
    step=3,
    reviewed=True,
    noise=0.4,
):
    """A project whose one recording carries labels generated by ``truth``.

    No video files: the labels' *identity* is written directly, which is all `calibrate`
    reads. That keeps the test about the solve rather than about video decoding (which
    ``test_gui_uncalibrated`` already covers).
    """
    project = Project.create(tmp_path / "proj", name="scratch", skeleton="fly38")
    LandmarkSet([Landmark(name=f"lm{i}", static=True) for i in range(n_static)]).save(
        project.root
    )

    rec = tmp_path / "flyA"
    rec.mkdir()
    for name in CAMERA_NAMES:
        (rec / f"{name}.mp4").write_bytes(b"\0" * (1000 + len(name)))
    entry = project.add_recording(rec)

    rng = np.random.default_rng(0)
    n_views = len(CAMERA_NAMES)
    static3d = rng.uniform(-25, 25, size=(n_static, 3))
    animal3d = rng.uniform(-4, 4, size=(n_frames, 38, 3))

    labels = Labels.empty(n_views, n_frames, 38)
    landmarks = LandmarkLabels.empty(
        n_views, n_frames, [f"lm{i}" for i in range(n_static)]
    )
    for t in range(n_frames):
        lm_px = np.asarray(truth.project(static3d)) + rng.normal(
            0, noise, (n_views, n_static, 2)
        )
        kp_px = np.asarray(truth.project(animal3d[t])) + rng.normal(
            0, noise, (n_views, 38, 2)
        )
        for v in range(n_views):
            for i in range(n_static):
                landmarks.set(v, t, i, lm_px[v, i])
            for p in range(0, n_kp, step):
                labels.set_gt(v, t, p, kp_px[v, p])
        if reviewed:
            labels.set_reviewed(t, True)

    identity = labels_identity(
        point_names=list(project.skeleton().point_names),
        camera_names=list(CAMERA_NAMES),
        n_frames=n_frames,
        image_sizes=SIZES,
    )
    save_labels(
        project.labels_path(entry), labels, identity=identity, landmarks=landmarks
    )
    return project, entry


def _centre_error_pct(truth, solved) -> float:
    a = np.stack([truth[n].position for n in CAMERA_NAMES])
    b = np.stack([solved[n].position for n in CAMERA_NAMES])
    ac, bc = a - a.mean(0), b - b.mean(0)
    u, s, vt = np.linalg.svd(bc.T @ ac)
    rot = u @ vt
    if np.linalg.det(rot) < 0:
        u[:, -1] *= -1
        rot = u @ vt
    scale = s.sum() / (bc**2).sum()
    err = np.linalg.norm(scale * (bc @ rot) - ac, axis=1)
    return float(100 * err.max() / np.linalg.norm(ac, axis=1).mean())


# -- the whole flow ------------------------------------------------------------


def test_the_whole_from_scratch_flow(tmp_path, truth, capsys):
    """Uncalibrated project + hand labels -> the rig they were generated from."""
    project, _ = _labelled_project(tmp_path, truth)
    assert project.calibration is None  # uncalibrated to begin with

    cli.main(
        [
            "calibrate",
            str(project.root),
            "--points",
            "both",
            "--focal-px",
            FOCAL,
            "--name",
            "from-labels",
            "--accept",
            "--log-level",
            "error",
        ]
    )
    out = capsys.readouterr().out
    assert "accepted" in out

    reloaded = Project.load(project.root)
    assert reloaded.calibration == "calibrations/from-labels.toml"

    cal = Calibration.load(project.root / "calibrations" / "from-labels.toml")
    assert cal.provenance["method"] == "labels_ba"
    assert cal.provenance["intrinsics"] == "given"
    assert cal.provenance["reviewed_only"] is True
    assert cal.units == "arbitrary"  # nothing pinned the scale
    assert cal.quality["rms_reproj_px"] < 2.0
    assert _centre_error_pct(truth, cal.cameras) < 1.0
    # The machine-readable report lands beside it.
    assert (project.root / "calibrations" / "from-labels.report.json").exists()


@pytest.mark.parametrize("points", ["landmarks", "keypoints", "both"])
def test_each_point_source_can_drive_the_solve(tmp_path, truth, points):
    """The operator's choice, per the ask: skeleton points, landmarks, or both."""
    project, _ = _labelled_project(tmp_path, truth)
    cli.main(
        [
            "calibrate",
            str(project.root),
            "--points",
            points,
            "--focal-px",
            FOCAL,
            "--name",
            points,
            "--log-level",
            "error",
        ]
    )
    cal = Calibration.load(project.root / "calibrations" / f"{points}.toml")
    assert cal.provenance["points"] == points
    assert _centre_error_pct(truth, cal.cameras) < 2.0


def test_nothing_is_accepted_without_the_flag(tmp_path, truth):
    """A bad solve must not be able to silently replace a good rig."""
    project, _ = _labelled_project(tmp_path, truth)
    cli.main(
        ["calibrate", str(project.root), "--focal-px", FOCAL, "--log-level", "error"]
    )
    assert (project.root / "calibrations" / "from-labels.toml").exists()
    assert Project.load(project.root).calibration is None


def test_dry_run_reports_readiness_and_writes_nothing(tmp_path, truth, capsys):
    project, _ = _labelled_project(tmp_path, truth)
    cli.main(
        [
            "calibrate",
            str(project.root),
            "--dry-run",
            "--focal-px",
            FOCAL,
            "--log-level",
            "error",
        ]
    )
    out = capsys.readouterr().out
    assert "Calibration readiness" in out
    assert "co-visibility" in out
    assert "static landmarks" in out
    assert not list((project.root / "calibrations").glob("*.toml"))


def test_a_known_distance_pins_the_units(tmp_path, truth):
    project, _ = _labelled_project(tmp_path, truth)
    cli.main(
        [
            "calibrate",
            str(project.root),
            "--points",
            "landmarks",
            "--focal-px",
            FOCAL,
            "--scale-from",
            "lm0,lm1=10.0",
            "--name",
            "scaled",
            "--log-level",
            "error",
        ]
    )
    cal = Calibration.load(project.root / "calibrations" / "scaled.toml")
    assert (cal.units, cal.scale_source) == ("mm", "known_distance")


# -- refusals ------------------------------------------------------------------


def test_missing_intrinsics_names_the_three_ways_to_supply_them(tmp_path, truth):
    """Focal length is not recoverable from these labels, so it must not be guessed."""
    project, _ = _labelled_project(tmp_path, truth)
    with pytest.raises(SystemExit, match="no intrinsics source"):
        cli.main(["calibrate", str(project.root), "--log-level", "error"])


def test_optics_derives_the_focal_from_a_datasheet(tmp_path, truth):
    """f_px = f_mm * W_px / W_mm -- two numbers off a lens/sensor datasheet.

    The values land on this rig's real focal (a long macro lens on a 1" sensor, which is
    what a microscope-like fly rig actually uses), so the solve succeeds too and the
    arithmetic is checked against something that works rather than in isolation.
    """
    project, _ = _labelled_project(tmp_path, truth)
    cli.main(
        [
            "calibrate",
            str(project.root),
            "--points",
            "landmarks",
            "--lens-mm",
            "233.209",
            "--sensor-mm",
            "10.0",
            "--name",
            "optics",
            "--log-level",
            "error",
        ]
    )
    cal = Calibration.load(project.root / "calibrations" / "optics.toml")
    assert cal.provenance["intrinsics"] == "optics"
    assert cal.cameras[CAMERA_NAMES[0]].intr[0] == pytest.approx(233.209 * 960 / 10.0)
    assert _centre_error_pct(truth, cal.cameras) < 2.0


def test_badly_wrong_intrinsics_fail_loudly_rather_than_quietly(tmp_path, truth):
    """A 4x-wrong focal must not yield a plausible-looking rig.

    This is the practical justification for refusing to guess intrinsics at all: with the
    focal wrong, the normalized coordinates the essential matrix and PnP work in are wrong
    and views cannot be placed. Failing here is the GOOD outcome -- the bad one would be a
    converged solve whose 3D is silently mis-scaled and mis-shaped.
    """
    project, _ = _labelled_project(tmp_path, truth)
    with pytest.raises(SystemExit, match="could not place view"):
        cli.main(
            [
                "calibrate",
                str(project.root),
                "--points",
                "landmarks",
                "--lens-mm",
                "50",
                "--sensor-mm",
                "8.8",
                "--name",
                "wrong",
                "--log-level",
                "error",
            ]
        )
    assert not (project.root / "calibrations" / "wrong.toml").exists()


def test_an_underdetermined_problem_is_refused_before_solving(tmp_path, truth, capsys):
    """It would converge to something plausible and then misproject everything."""
    project, _ = _labelled_project(
        tmp_path, truth, n_static=0, n_frames=1, n_kp=2, step=1
    )
    with pytest.raises(SystemExit, match="under-determined"):
        cli.main(
            [
                "calibrate",
                str(project.root),
                "--focal-px",
                FOCAL,
                "--log-level",
                "error",
            ]
        )
    assert "refusing" in capsys.readouterr().out
    assert not list((project.root / "calibrations").glob("*.toml"))


def test_unreviewed_frames_are_excluded_by_default(tmp_path, truth):
    """A half-labeled frame biases a track, and no residual reveals it afterwards."""
    project, _ = _labelled_project(tmp_path, truth, reviewed=False)
    with pytest.raises(SystemExit, match="nothing to calibrate from"):
        cli.main(
            [
                "calibrate",
                str(project.root),
                "--focal-px",
                FOCAL,
                "--log-level",
                "error",
            ]
        )
    # ...and can be opted into.
    cli.main(
        [
            "calibrate",
            str(project.root),
            "--include-unreviewed",
            "--points",
            "landmarks",
            "--focal-px",
            FOCAL,
            "--name",
            "unrev",
            "--log-level",
            "error",
        ]
    )
    cal = Calibration.load(project.root / "calibrations" / "unrev.toml")
    assert cal.provenance["reviewed_only"] is False


def test_a_project_with_no_labels_says_so(tmp_path):
    project = Project.create(tmp_path / "proj")
    with pytest.raises(SystemExit, match="nothing to calibrate from"):
        cli.main(["calibrate", str(project.root), "--log-level", "error"])


def test_a_bad_scale_spec_is_a_clear_error(tmp_path, truth):
    project, _ = _labelled_project(tmp_path, truth)
    with pytest.raises(SystemExit, match="could not read --scale-from"):
        cli.main(
            [
                "calibrate",
                str(project.root),
                "--focal-px",
                FOCAL,
                "--scale-from",
                "nonsense",
                "--log-level",
                "error",
            ]
        )


def test_a_scale_spec_naming_an_unknown_track_lists_the_real_ones(tmp_path, truth):
    project, _ = _labelled_project(tmp_path, truth)
    with pytest.raises(SystemExit, match="but the solve's tracks are"):
        cli.main(
            [
                "calibrate",
                str(project.root),
                "--focal-px",
                FOCAL,
                "--scale-from",
                "nope,alsonope=1.0",
                "--log-level",
                "error",
            ]
        )
